services:
  app:
    build: .
    container_name: tycord-instant-messaging
    environment:
      - DATABASE_URL=${DEV_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=${PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - .:/app